ungrouped:
  hosts:
    # ansible_host:
    # TODO
loadbalancer:
  hosts:
    localhost:
      ansible_host: 0.0.0.0
      ansible_connection: local 
      ansible_user: root
app_group:
  hosts:
    # TODO
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_port: 2223
      ansible_connection: ssh
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_port: 2224
      ansible_connection: ssh
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_port: 2225
      ansible_connection: ssh
      ansible_user: root